# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pickle

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(383, 339)
        Dialog.setStyleSheet("*{\n"
" color:  white;\n"
" background: rgba(0 , 0, 0, 0);\n"
"}")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(250, 130, 131, 101))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.ResultadosFinales = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.ResultadosFinales.setContentsMargins(0, 0, 0, 0)
        self.ResultadosFinales.setObjectName("ResultadosFinales")
        self.titulo_1 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.titulo_1.setObjectName("titulo_1")
        self.ResultadosFinales.addWidget(self.titulo_1)
        self.Resultado = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Resultado.setStyleSheet("QLabel{\n"
" color: \"red\";\n"
"}")
        self.Resultado.setText("")
        self.Resultado.setObjectName("Resultado")
        self.ResultadosFinales.addWidget(self.Resultado)
        self.titulo_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.titulo_2.setObjectName("titulo_2")
        self.ResultadosFinales.addWidget(self.titulo_2)
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget_2)
        self.progressBar.setStyleSheet("QProgressBar{\n"
" background: rgba(24, 115, 39);\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.ResultadosFinales.addWidget(self.progressBar)
        self.verificar = QtWidgets.QPushButton(Dialog)
        self.verificar.setGeometry(QtCore.QRect(50, 310, 141, 21))
        self.verificar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.verificar.setStyleSheet("QPushButton{\n"
" border-radius: 10%;\n"
"background: rgb(40, 191, 65);\n"
"}\n"
"QPushButton:hover{\n"
" border-radius: 10%;\n"
" background: rgba(24, 115, 39);\n"
" color: white;\n"
"}")
        self.verificar.setObjectName("verificar")
        self.datos = QtWidgets.QPlainTextEdit(Dialog)
        self.datos.setGeometry(QtCore.QRect(10, 90, 229, 215))
        self.datos.setStyleSheet("QPlainTextEdit{\n"
" border-radius: 10%;\n"
" background:  rgba(66, 66, 66);\n"
"}")
        self.datos.setObjectName("datos")
        self.titulo_inferior = QtWidgets.QLabel(Dialog)
        self.titulo_inferior.setGeometry(QtCore.QRect(10, 70, 227, 16))
        self.titulo_inferior.setObjectName("titulo_inferior")
        self.titulo = QtWidgets.QPlainTextEdit(Dialog)
        self.titulo.setGeometry(QtCore.QRect(10, 40, 227, 27))
        self.titulo.setStyleSheet("QPlainTextEdit{\n"
" border-radius: 10%;\n"
" background: rgba(66, 66, 66);\n"
"}")
        self.titulo.setObjectName("titulo")
        self.titulo_superior = QtWidgets.QLabel(Dialog)
        self.titulo_superior.setGeometry(QtCore.QRect(10, 0, 227, 49))
        self.titulo_superior.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.titulo_superior.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.titulo_superior.setObjectName("titulo_superior")
        
        self.retranslateUi(Dialog)
        self.verificar.clicked.connect(self.enviar)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def enviar(self):
        titulo = self.titulo.toPlainText()
        cuerpo = self.datos.toPlainText()
        noticia = titulo + "\n" + cuerpo
        load_model = pickle.load(open('final_model.sav', 'rb'))
        prediction = load_model.predict([noticia])
        prob = load_model.predict_proba([noticia])
        self.Resultado.setText(str(prediction[0]))
        

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Detector de Noticias falsas"))
        self.titulo_1.setText(_translate("Dialog", "Noticia es:"))
        self.titulo_2.setText(_translate("Dialog", "Porcentaje de validez:"))
        self.verificar.setText(_translate("Dialog", "Verificar"))
        self.titulo_inferior.setText(_translate("Dialog", "Ingrese la noticia a evaluar:"))
        self.titulo_superior.setText(_translate("Dialog", "Ingrese el titulo del articulo:"))
